version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
